[package]
name = "rtop"
version = "0.1.0"
edition = "2024"
authors = ["Immanuel Raja Jeyaraj <irj@sefier.com>"]
license = "GPL-2.0-or-later"
description = "A lightweight terminal system monitor (TUI) for Linux"
readme = "README.md"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.28.1"
sysinfo = "0.30.13"
portable-pty = "0.8.1"
strip-ansi-escapes = "0.2.1"
